### ISSUE TITLE
java.lang.UnsupportedOperationException: CRaC or CRIU support is not enabled

### ISSUE THREAD

**Issue by willr3** [jdmcclur/pingPerf#2]
I am seeing UnsupportedOperationExceptions when trying to run `./build.semeru.sh`
Are those exceptions indicative of the build failing?  The exception is logged three times during step 8/9 for the podman builds but the script exit code is 0. Is there a prerequisite we need to resolve the exceptions? 

```
java.lang.UnsupportedOperationException: CRaC or CRIU support is not enabled
    at java.base/openj9.internal.criu.InternalCRIUSupport.checkpointJVM(InternalCRIUSupport.java:1005)
    at java.base/jdk.crac.CRIUSupportContext.checkpointJVM(Core.java:122)
    at java.base/jdk.crac.Core.checkpointRestore(Core.java:62)
    at java.base/openj9.internal.tools.attach.target.DiagnosticUtils.lambda$doCheckpointJVM$1(DiagnosticUtils.java:574)
    at java.base/java.lang.Thread.run(Thread.java:853)
jdk.crac.CheckpointException: Default CheckpointException
    at java.base/jdk.crac.Core.checkpointRestore(Core.java:64)
    at java.base/openj9.internal.tools.attach.target.DiagnosticUtils.lambda$doCheckpointJVM$1(DiagnosticUtils.java:574)
    at java.base/java.lang.Thread.run(Thread.java:853)
Caused by: java.lang.UnsupportedOperationException: CRaC or CRIU support is not enabled
    at java.base/openj9.internal.criu.InternalCRIUSupport.checkpointJVM(InternalCRIUSupport.java:1005)
    at java.base/jdk.crac.CRIUSupportContext.checkpointJVM(Core.java:122)
    at java.base/jdk.crac.Core.checkpointRestore(Core.java:62)
    ... 2 more
```

**Comment by jdmcclur** [comment]
Did you update the .env file with the token to get criu? If not, let me know your email (or send me a note at jdmcclur@us.ibm.com) and I can get that to you.

**Comment by willr3** [comment]
email sent from wreicher@redhat.com

**Comment by willr3** [comment]
I added the token to the .env but I still see the UnsupportedOperationException when running `./build.semeru.sh` durng `STEP 8/9: RUN ./startQuarkus.sh`
Are there local system requirement?

We initially ran into issues where podman did not have cpuset permissions and resolved those following the instructions here: https://github.com/containers/podman/blob/main/troubleshooting.md#26-running-containers-with-resource-limits-fails-with-a-permissions-error

**Comment by willr3** [comment]
The podman build was using cached containers despite the change to .env. 
```
--> Using cache <hash>
```
I purged everything with
```
podman container prune -f
podman image prune -f -a
```
Now I'm able to run `./build.semeru.sh` without the UnsupportedOperationException.
